files:
  include: 'static/styles/**/*.scss'
  ignore: 'static/styles/vendor/**/*.scss'

rules:
  class-name-format:
    - 2
    -
      convention: hyphenatedbem
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  quotes:
    - 2
    -
      style: double
  single-line-per-selector: 0 
  placeholder-in-extend: 0
  nesting-depth:
    - 1
    -
      max-depth: 3

  no-misspelled-properties:
    - 1
    - extra-properties: ['grid-column-gap']
  no-url-domains: 0
  no-url-protocols: 0
